version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "10:00"
    timezone: EST
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ava
    versions:
    - "> 3.12.1, < 4"
  - dependency-name: parse-path
    versions:
    - 4.0.3
  - dependency-name: bent
    versions:
    - 7.3.12
