name: e2e
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    name: Run e2e tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browser dependencies
        run: pnpx playwright install --with-deps
      - name: Run end-to-end tests using Playwright
        run: "pnpm test:e2e"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      