name: Create prereleases from “next” branch

on:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prerelease:
    # prevents this action from running on forks
    if: github.repository == 'gfscott/eleventy-plugin-embed-everything'

    name: Prerelease packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Following Changesets prerelease procedures:
      # https://github.com/changesets/changesets/blob/main/docs/prereleases.md
      # - Currently not pushing git tags to keep things moderately cleaner in the repo
      # - actions/checkout README suggests github-actions@github.com for git user:
      #     https://github.com/actions/checkout/blob/main/README.md#push-a-commit-using-the-built-in-token
      - name: Enter prerelease mode and publish to npm with changesets
        run: |
          pnpm changeset pre enter next
          pnpm changeset version
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Enter prerelease mode and version packages"
          pnpm changeset publish --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
