name: Sync “next” branch with main

on:
  # Only triggered after CI tests workflow
  workflow_run:
    workflows: [CI]
    types: [completed]
  # Only runs on main branch
  branches:
    - main

jobs:
  sync:
    # prevents this action from running on forks
    if: github.repository == 'gfscott/eleventy-plugin-embed-everything'

    name: Sync “next” branch with main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # Source: modified from a shopify/hydrogen workflow:
      # https://github.com/Shopify/hydrogen/blob/main/.github/workflows/sync_main.yml
      - name: Push to “next” branch
        run: |
          git show-ref
          git push origin HEAD:next --force
